version: '3.9'

services:
  app: &app_base
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp:delegated
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  bundle: